openapi: 3.0.1
info:
  title: Daily Banking Product API
  version: 1.0.28
  description: >-
    This API provides the basic functions needed in the offering discovery process, such as search product offering, retrieve information about specific product offering or parts of it
  contact:
    name: Person
    email: amdocs@nl.abnamro.com
  x-apiType: "enterprise"
servers:
  - url: https://api-st-iag.nl.eu.abnamro.com/daily-banking/products/v1
    description: ST server
  - url: https://api-et-iag.nl.eu.abnamro.com/daily-banking/products/v1
    description: ET server
  - url: https://api-pr-iag.nl.eu.abnamro.com/daily-banking/products/v1
    description: PR server
paths:
  /:
    get:
      tags:
        - product-offering
      operationId: getDailyBankingProductList
      summary: retrieves commercial product offerings based on the search criterion
      description: |-
        The operation returns all commercial product offerings that match the given criteria in the input regardless of qualification rules (but qualification can be expressed as a search criterion). For localized information, the operation returns only the entries matching the 'Accept-Language' header or the default language if none is specified.\
          Filtering values are combined in the OR operation
      parameters:
        - name: Subject-Token-Type
          in: header
          required: false
          description: specifies the authorisation mechanism
          schema:
            $ref: '#/components/headers/Subject-Token-Type'
        - name: Subject-Token
          in: header
          required: false
          description: the consumer application
          schema:
            $ref: '#/components/headers/Subject-Token'
        - name: Consumer-Id
          in: header
          required: true
          description: the consumer application
          schema:
            $ref: '#/components/headers/Consumer-Id'
        - name: Trace-Id
          in: header
          required: true
          description: the consumer application
          schema:
            $ref: '#/components/headers/Trace-Id'
        - name: Accept-Language
          in: header
          description: the consumer application
          schema:
            $ref: '#/components/headers/Accept-Language'
        - name: businessLine
          in: query
          description: further refinement of the products within given category
          schema:
            type: string
            enum:
              - RETAIL
              - MEES_PIERSON
              - SMALL_AND_MEDIUM_ENTERPRISES
              - LARGE_CORPORATES
              - INTERNATIONAL_BANKING
          style: form
          explode: false
          example: RETAIL
        - name: productLine
          in: query
          description: Basic split of banking products
          schema:
            type: string
            enum:
              - SAVINGS
              - PAYMENTS
              - INSURANCES
              - CASH
              - CREDITS
              - SECURITIES
              - PENSIONS
              - ADVICES
              - MONEY_MARKETS
              - MORTGAGES
              - LOANS
          style: form
          explode: false
          example: SAVINGS
        - name: productLineCategory
          in: query
          description: |
            further split of banking products within the product line; the actual set of values depends on the product line \
              Be advised, this is not free text. Please check with the Catalogue administration before using it. \
              For SAVINGS the relevant categories would be: \
                - COMMERCIAL_CUSTOMIZED_SAVINGS_ACCOUNTS \
                - COMMERCIAL_STANDARD_SAVINGS_ACCOUNTS \
                - INVESTMENT_SAVING_ACCOUNTS \
                - STANDARD_SAVINGS_ACCOUNTS \
                - CHILDRENS_SAVINGS_ACCOUNTS \
                - CUSTOMIZED_SAVINGS_ACCOUNTS \
                - INTERNATIONAL_STANDARD_SAVINGS_ACCOUNTS
                
              @TODO:\
                Add reference documentation about the values and their correlation with the productLine values above and their maintenance process
          schema:
            type: string
          style: form
          explode: false
          example: INVESTMENT_SAVING_ACCOUNTS
        - name: productsGroup
          in: query
          description: >-
            Banking product grouped by appearance type
          schema:
            type: string
            enum:
              - PAYMENT_INSTRUMENTS
              - SAVINGS_ACCOUNTS
              - ACCESS_INSTRUMENTS
              - STATEMENTS_AND_REPORTS
              - INSURED_SERVICES
          style: form
          explode: false
        - name: country
          in: query
          description: >-
            three letters country code of the country where the product is sold, in ISO 3166 format. A special country code 'SEP' is used for aggregating the SEPA member countries.
          schema:
            type: string
            pattern: '[A-Z]{3}'
          style: form
          explode: false
        - name: "customerId"
          description: >-
            non-mandatory parameter; if known then the result will be filtered to match only product offering for which the given customer is eligible
          schema:
            type: string
          in: query
          example: 002468097531
      responses:
        200:
          description: Full set of product offering terms and conditions
          headers:
            Trace-Id:
              $ref: '#/components/headers/Trace-Id'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductsList'
        400:
          description: parameter incorrect.
          headers:
            Trace-Id:
              $ref: '#/components/headers/Trace-Id'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationCustomError'
        401:
          headers:
            Trace-Id:
              $ref: '#/components/headers/Trace-Id'
          description: |
            "Authorization Error"

            Detailed Error List: 
            ---
            - SUBJECT_TOKEN_INVALID
              > Valid subject-token is required.
            - SUBJECT_TOKEN_MISSING
              > The Subject-Token header is required.
            - SUBJECT_TOKEN_TYPE_INVALID
              > The Subject-Token-Type header should be 'MSEC'.
            - SUBJECT_TOKEN_TYPE_MISSING
              > The Subject-Token-Type header is required.
          content: 
            "application/json":
              schema:
                $ref: '#/components/schemas/ApplicationCustomError'
              example:
                  {
                   errors: [
                             {
                              "code": "SUBJECT_TOKEN_MISSING",
                              "message": "The Subject Token header is required.",
                              "traceId": "924bd142-6514-445c-9e01-486820d94263",
                              "status": 401
                             }
                           ]
                  }
        403:
          headers:
            Trace-Id:
              $ref: '#/components/headers/Trace-Id'
          description: |
            "Access Forbidden"

            Detailed Error List: 
            ---
            - SUBJECT_NOT_ALLOWED
              > The Subject (End User) is not allowed to use the specific operation.
          content: 
            "application/json":
              schema:
                $ref: "#/components/schemas/ApplicationCustomError"
              example:
                  {
                   errors: [
                             {
                              "code": "SUBJECT_NOT_ALLOWED",
                              "message": "The Subject (End User) is not allowed to use the specific operation.",
                              "traceId": "6be9522f-ff5f-4932-8243-66c154880a1a",
                              "status": 403
                             }
                           ]
                  }
        406:
          description: |
            not acceptable. this will not be implemented as the service will always return the Dutch version in case the language requested is not understood or cannot be served
          headers:
            Trace-Id:
              $ref: '#/components/headers/Trace-Id'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationCustomError'
        500:
          description: >-
            An unexpected error has occurred. The error has been logged and is
            being investigated.
          headers:
            Trace-Id:
              $ref: '#/components/headers/Trace-Id'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationCustomError'
  /{productId}/fulfillment:
    parameters:
      - name: Subject-Token-Type
        in: header
        required: false
        description: specifies the authorisation mechanism
        schema:
          $ref: '#/components/headers/Subject-Token-Type'
      - name: Subject-Token
        in: header
        required: false
        description: the consumer application
        schema:
          $ref: '#/components/headers/Subject-Token'
      - name: Consumer-Id
        in: header
        required: true
        description: the consumer application
        schema:
          $ref: '#/components/headers/Consumer-Id'
      - name: Trace-Id
        in: header
        required: true
        description: the consumer application
        schema:
          $ref: '#/components/headers/Trace-Id'
      - $ref: '#/components/parameters/ProductId'
    get:
      tags:
        - product-offering
      summary: exposes fulfillment attributes
      description: >-
        provides to order management system with the structure of attributes needed for fulfilment process per product engine
      operationId: getDailyBankingProductFulfillmentAttributes
      responses:
        200:
          description: Full set of fulfilment needed attributes split per backend adminstration (product engine)
          headers:
            Trace-Id:
              $ref: '#/components/headers/Trace-Id'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductFulfillmentParameters'
        401:
          headers:
            Trace-Id:
              $ref: '#/components/headers/Trace-Id'
          description: |
            "Authorization Error"

            Detailed Error List: 
            ---
            - SUBJECT_TOKEN_INVALID
              > Valid subject-token is required.
            - SUBJECT_TOKEN_MISSING
              > The Subject-Token header is required.
            - SUBJECT_TOKEN_TYPE_INVALID
              > The Subject-Token-Type header should be 'MSEC'.
            - SUBJECT_TOKEN_TYPE_MISSING
              > The Subject-Token-Type header is required.
          content: 
            "application/json":
              schema:
                $ref: '#/components/schemas/ApplicationCustomError'
              example:
                  {
                   errors: [
                             {
                              "code": "SUBJECT_TOKEN_MISSING",
                              "message": "The Subject Token header is required.",
                              "traceId": "924bd142-6514-445c-9e01-486820d94263",
                              "status": 401
                             }
                           ]
                  }
        403:
          headers:
            Trace-Id:
              $ref: '#/components/headers/Trace-Id'
          description: |
            "Access Forbidden"

            Detailed Error List: 
            ---
            - SUBJECT_NOT_ALLOWED
              > The Subject (End User) is not allowed to use the specific operation.
          content: 
            "application/json":
              schema:
                $ref: "#/components/schemas/ApplicationCustomError"
              example:
                  {
                   errors: [
                             {
                              "code": "SUBJECT_NOT_ALLOWED",
                              "message": "The Subject (End User) is not allowed to use the specific operation.",
                              "traceId": "6be9522f-ff5f-4932-8243-66c154880a1a",
                              "status": 403
                             }
                           ]
                  }
        404:
          description: The requested offering was not found in our system.
          headers:
            Trace-Id:
              $ref: '#/components/headers/Trace-Id'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationCustomError'
        500:
          description: >-
            An unexpected error has occurred. The error has been logged and is
            being investigated.
          headers:
            Trace-Id:
              $ref: '#/components/headers/Trace-Id'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationCustomError'
  /{productId}/eligibility-check:
    parameters:
      - name: Subject-Token-Type
        in: header
        required: false
        description: specifies the authorisation mechanism
        schema:
          $ref: '#/components/headers/Subject-Token-Type'
      - name: Subject-Token
        in: header
        required: false
        description: the consumer application
        schema:
          $ref: '#/components/headers/Subject-Token'
      - name: Consumer-Id
        in: header
        required: true
        description: the consumer application
        schema:
          $ref: '#/components/headers/Consumer-Id'
      - name: Trace-Id
        in: header
        required: true
        description: the consumer application
        schema:
          $ref: '#/components/headers/Trace-Id'
      - $ref: '#/components/parameters/ProductId'
    post:
      tags: 
        - product-offering
      summary: verifies if customer qualifies for the given product
      operationId: checkDailyBankingProductEligibility
      description: >-
        the operation performs a deep eligibility check, including the qualification rules involving operational data, such as the presence of a current account or limitations regarding the number of savings products.
      requestBody:
        description: "the customer identification"
        required: true
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/Customer"
            example: 
              identificationType: BC_ID
              id: 0002468097531
                     
      responses:
        204:
          description: "customer is eligible for yet another instance of the requested product; no further content is provided"
          headers:
            Trace-Id:
              $ref: '#/components/headers/Trace-Id'
        400:
          description: >-
            not eligible
            returned in one of the situations below; please check the error message for details: 
              * the customer is not eligible for (yet another instance of) the requested offering 
              * the customer cannot be found in the operational data 
              * the customer parameters are insufficient for assessing the eligibility 
              * some of the downstream systems do not respond and the eligibility cannot be assessed w/o the related data
          headers:
            Trace-Id:
              $ref: '#/components/headers/Trace-Id'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationCustomError'
        401:
          headers:
            Trace-Id:
              $ref: '#/components/headers/Trace-Id'
          description: |
            "Authorization Error"

            Detailed Error List: 
            ---
            - SUBJECT_TOKEN_INVALID
              > Valid subject-token is required.
            - SUBJECT_TOKEN_MISSING
              > The Subject-Token header is required.
            - SUBJECT_TOKEN_TYPE_INVALID
              > The Subject-Token-Type header should be 'MSEC'.
            - SUBJECT_TOKEN_TYPE_MISSING
              > The Subject-Token-Type header is required.
          content: 
            "application/json":
              schema:
                $ref: '#/components/schemas/ApplicationCustomError'
              example:
                  {
                   errors: [
                             {
                              "code": "SUBJECT_TOKEN_MISSING",
                              "message": "The Subject Token header is required.",
                              "traceId": "924bd142-6514-445c-9e01-486820d94263",
                              "status": 401
                             }
                           ]
                  }
        403:
          headers:
            Trace-Id:
              $ref: '#/components/headers/Trace-Id'
          description: |
            "Access Forbidden"

            Detailed Error List: 
            ---
            - SUBJECT_NOT_ALLOWED
              > The Subject (End User) is not allowed to use the specific operation.
          content: 
            "application/json":
              schema:
                $ref: "#/components/schemas/ApplicationCustomError"
              example:
                  {
                   errors: [
                             {
                              "code": "SUBJECT_NOT_ALLOWED",
                              "message": "The Subject (End User) is not allowed to use the specific operation.",
                              "traceId": "6be9522f-ff5f-4932-8243-66c154880a1a",
                              "status": 403
                             }
                           ]
                  }
        404:
          description: The requested offering was not found in our system.
          headers:
            Trace-Id:
              $ref: '#/components/headers/Trace-Id'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationCustomError'
        500:
          description: >-
            An unexpected error has occurred. The error has been logged and is
            being investigated.
          headers:
            Trace-Id:
              $ref: '#/components/headers/Trace-Id'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationCustomError'
  /{productId}/configuration-validation:
    parameters:
      - name: Subject-Token-Type
        in: header
        required: false
        description: specifies the authorisation mechanism
        schema:
          $ref: '#/components/headers/Subject-Token-Type'
      - name: Subject-Token
        in: header
        required: false
        description: the consumer application
        schema:
          $ref: '#/components/headers/Subject-Token'
      - name: Consumer-Id
        in: header
        required: true
        description: the consumer application
        schema:
          $ref: '#/components/headers/Consumer-Id'
      - name: Trace-Id
        in: header
        required: true
        description: the consumer application
        schema:
          $ref: '#/components/headers/Trace-Id'
      - $ref: '#/components/parameters/ProductId'
    post:
      tags: 
        - product-offering
      summary: validates the configuration values given for the product
      description: validates the configuration values given for the product
      operationId: validateDailyBankingProductConfiguration
      requestBody:
        description: |
          the customer chosen configuration\
            ##### be advised that in the example the itemId intentionally start with the particle found in "parentItemId" while in practice does not have to be this way
        required: true
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/ConfigurationValues"
            example: 
              - itemId: card.colour
                itemValue: GREEN
                parentItemId: card
              - itemId: card.name_on_card
                parentItemId: card
                itemValue: Her. NoSQL Allowed
      responses:
        204:
          description: "customer chosen configuration is valid; no further content is provided"
          headers:
            Trace-Id:
              $ref: '#/components/headers/Trace-Id'
        400:
          description: >-
            not eligible; please check the error message for details. \
            
            returned in one of the situations below: 
              * the customer is not eligible for (yet another instance of) the requested offering 
              * the customer cannot be found in operational data 
              * the customer parameters are insufficient for assessing the eligibility 
              * some of the downstream systems do not respond and the eligibility cannot be assessed w/o the related data
          headers:
            Trace-Id:
              $ref: '#/components/headers/Trace-Id'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationCustomError'
        401:
          headers:
            Trace-Id:
              $ref: '#/components/headers/Trace-Id'
          description: |
            "Authorization Error"

            Detailed Error List: 
            ---
            - SUBJECT_TOKEN_INVALID
              > Valid subject-token is required.
            - SUBJECT_TOKEN_MISSING
              > The Subject-Token header is required.
            - SUBJECT_TOKEN_TYPE_INVALID
              > The Subject-Token-Type header should be 'MSEC'.
            - SUBJECT_TOKEN_TYPE_MISSING
              > The Subject-Token-Type header is required.
          content: 
            "application/json":
              schema:
                $ref: '#/components/schemas/ApplicationCustomError'
              example:
                  {
                   errors: [
                             {
                              "code": "SUBJECT_TOKEN_MISSING",
                              "message": "The Subject Token header is required.",
                              "traceId": "924bd142-6514-445c-9e01-486820d94263",
                              "status": 401
                             }
                           ]
                  }
        403:
          headers:
            Trace-Id:
              $ref: '#/components/headers/Trace-Id'
          description: |
            "Access Forbidden"

            Detailed Error List: 
            ---
            - SUBJECT_NOT_ALLOWED
              > The Subject (End User) is not allowed to use the specific operation.
          content: 
            "application/json":
              schema:
                $ref: "#/components/schemas/ApplicationCustomError"
              example:
                  {
                   errors: [
                             {
                              "code": "SUBJECT_NOT_ALLOWED",
                              "message": "The Subject (End User) is not allowed to use the specific operation.",
                              "traceId": "6be9522f-ff5f-4932-8243-66c154880a1a",
                              "status": 403
                             }
                           ]
                  }
        404:
          description: The requested offering was not found in our system.
          headers:
            Trace-Id:
              $ref: '#/components/headers/Trace-Id'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationCustomError'
        500:
          description: >-
            An unexpected error has occurred. The error has been logged and is
            being investigated.
          headers:
            Trace-Id:
              $ref: '#/components/headers/Trace-Id'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationCustomError'
components:
  responses:
    ServerErrors:
      description: |
        "Server made a Boo-Boo!"

        Detailed Error List:
        ---
        - INTERNAL_SERVER_ERROR
          > Internal server error occurred
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApplicationCustomError'
          example:
            {
              errors: [
              {
                "code": "INTERNAL_SERVER_ERROR",
                "message": "Internal server error occurred",
                "traceId": "XX1234",
                "status": 500
              }
              ]
            }
  headers:
    Subject-Token-Type:
      description: "Indicates which type of session the user is logged in. Example: MSEC."
      schema: 
        type: string
        enum:
          - MSEC
          - ENTERPRISE_TOKEN
        example: MSEC
    Subject-Token:
      description: "Unique token identifying the session of the logged in user."
      required: true
      schema: 
        type: string
      example: "VGhpcyBpcyBhIG5pY2UgdGV4dCBlbmNvZGVkIGluIEJhc2U2NA=="
    Consumer-Id:
      description: "Unique value for consumer application calling the API "
      required: true
      schema:
        type: string
        example: "DCPB"
    Trace-Id:
      description: "Unique end-2-end trace id received from the consumer"
      required: true
      schema:
        type: string
        example: "16258284-86af-4d65-8cc9-6b4a471f0207"
    Accept-Language:
      description: |-
        the list o languages accepted by the consumer; is strongly recommended, otherwise, the default language decided by the backend is provided. If the content is not found in the requested language/s then the content in the 'nl' language is returned for that object(!)
      schema:
        type: string
        example: 'en'
  parameters:
    Consumer-Id:
      in: "header"
      name: "Consumer-Id"
      description: |
        A unique value for consumer applications calling the API
      required: true
      schema:
        type: string
        example: "DCPB"
    Trace-Id:
      name: "Trace-Id"
      in: header
      description: |
        The unique end-2-end trace id received from the consumer
      required: true
      schema:
        type: string
        example: "16258284-86af-4d65-8cc9-6b4a471f0207"
    ProductId:
      name: "productId"
      in: "path"
      required: true
      description: |
        the identifier of the product offering for which the sales context is requested
      schema:
        type: string
        example: '001294'

  schemas:
    Customer:
      type: object
      oneOf:
        - $ref: "#/components/schemas/CustomerIdentification"
        - $ref: "#/components/schemas/CustomerCharacteristics"
    CustomerIdentification:
      type: object
      description: |
        customer BC ID or party id
      required: 
        - "id"
      properties:
        identificationType:
          description: |- 
            the type of customer identifier. this refers to the customer's representation identifier within the financial institution's registry, not to the civil or social identification
          type: string
          default: BC_ID
          example: BC_ID
          enum: 
            - PARTY_ID
            - BC_ID
            - EXTERNAL
        id:
          description: >-
            customer's representation identifier within the financial institution's registry
          type: string
          example: 000123456789
      example: 
        identificationType: BC_ID
        id: 0002468097531
    CustomerCharacteristics:
      type: object
      description: |-
        an avatar that holds all the attributes needed for assessing the eligibility of a customer \
          be advised that there is no operational data attached to the avatar so only the session data can be used
      required: 
        - "relationCategory"
      properties:
        relationCategory:
          type: string
          pattern: '\d{2}'
          description: zero left padded relation category
          example: "14"
        clientGroupCode:
          type: string
          pattern: '\d{4}'
          description: |
            zero left padded client group code
          example: "0456"
        age:
          type: integer
          description: |
            the age of the (avatar) customer in years
          example: 108
        customerLifeCycleStatus:
          description: |-
            the status of the customer is mapped to the known registration status codes in BCDB (e.g. a customer having an account with AAB is in registration status 4)
               - ACTIVE = the customer is known to the bank and it has active agreeemnt/s
               - PROSPECTIVE = the customer did not pass through the onboarding process but shows interest to purchase financial services/products
               - SUSPENDED = the customer does not have active agreements with the bank but did not express the wish to terminate business with the financial institution
               - TERMINATED = the customer does not have an active agreement with the financial institution and there is no wish for the collaboration to continue.
          type: string
          default: ACTIVE
          example: ACTIVE
          enum: 
            - ACTIVE
            - PROSPECTIVE
            - SUSPENDED
            - TERMINATED
        financialRiskScore:
          description: |
            the financial risk assessment score; a.k.a KYCScore
          type: integer
          example: 48
        financialRiskReassessmentDate:
          description: |
            when the financial risk will be reassessed. a.k.a. KYC Reassessment Date
          type: string
          format: date
          example: "2019-12-11"
        debtorStatus:
          description: |-
            shows if the customer has unpaid debts over to the financial institution and if so, which is the collection status. a.k.a. "Flanderijn status"
              - N_A = the customer has no known debts to the financial institution
              - POINT_OF_NO_RETURN = the customer has old debts with the financial institution and the institution intends to initiate legal collection of the debts
              - FLAGGED = the customer has recent debts with the financial institution and the institution intends to amiably pursue debt collection
          type: string
          enum:
            - N_A
            - POINT_OF_NO_RETURN
            - FLAGGED
    ApplicationCustomError:
      type: object
      required: 
        - "errors"
      properties:
        errors:
          type: array
          minItems: 1 
          maxItems: 5
          description: |
            List of application errors.
          items:
            $ref: '#/components/schemas/ErrorItem'
    ErrorItem:
      type: object
      required:
         - "code"
         - "message"
         - "status"
      properties:
        status:
          type: integer
          description: |
            unique status code identifying the type of issue. Can be filled with the HTTP status code, for example.
        code:
          type: string
          description: |
            Application internal error code.
        traceId:
          type: string
          description: |
            Application internal error trace Id.
        message:
          type: string
          description: |
            Error message, descriptive for the investigating party. For example, for consumer error, it should hint where the request could change to get a successful response.
      description: List of application errors.
    ProductsList:
      type: object
      required: 
        - "products"
      properties:
        products:
          type: array
          minItems: 0
          maxItems: 2000
          items:
            $ref: '#/components/schemas/ProductBrief'
    ProductBrief:
      description: |
        a 360 view of the product offering
      type: object
      required: 
        - "productId"
      properties:
        productId:
          type: string
          description: unique id of the offering
          example: "0293853491938"
        productName:
          type: string
          description: |
            localized name of the offering; could be used in front-end
          example: "Future Savings"
        productShortDescription:
          type: string
          description: |
            localized description/short briefing of the offering; could be used in front-end
          example: "Just a place where to keep your money until your kid starts college"
        productDocumentationURL:
          description:  |
            the location of an electronic document (web page, pdf, etc) containing a detailed description of the product offering and/or its terms and conditions
          type: string
          pattern: "url"
          example: 'https://developer-pr-iag.nl.eu.abnamro.com/rest-standards-and-guidelines/yaml-guidelines/#151'
    ProductImplementationBase:
      description: >-
        this is the minimum set of parameters for a base product to be instantiated; the correlation between the attributes set and enforcement of their split toward the correct base administration should be done in the Order Management System. \
          Here is just the definition of what has to be sent for a a Product Offering, per instantiation administration. \
          Currently, most of the administrations are collecting the instantiation parameters from GRV tables. The 'fulfillmentConfigurationId' is the 'GRV-code'. Once the correct set of parameters is identified and agreed, the 'fulfillmentConfigurationId' will become obsolete and replaced with the actual set of parameters, giving the flexibility to separate between various instantiation administrations.
      type: object
      required: 
        - "fulfillmentConfigurationId"
        - "fulfillmentAdministration"
      properties:
        fulfillmentAdministration:
          description: the backend adminsitration that implements a subset of financial services and isntantiate (a part of) an agreement
          type: string
          example: CRC
        fulfillmentConfigurationId:
          description: a minimal code needed by the fulfillment administration to be able to instantiate (a part of) an agreement
          type: string
          example: 42
    AccountingFulfillmentParameters:
      description: all the parameters needed to instantiate the product in Financial Accounting System (FRS)
      allOf:
        - $ref: '#/components/schemas/ProductImplementationBase'
      example:
        fulfillmentAdministration: "Financial Accounting Registry (FRS)"
        fulfillmentConfigurationId: "42"
    BillingFulfillmentParameters:
      description: all the parameters needed to instantiate the product in Generiek Tariferen (GT). \
        
        Currently, GT is collecting the instantiated products from P&C and does not participate in the fulfillment process.
      allOf:
        - $ref: '#/components/schemas/ProductImplementationBase'
      properties:
        productId:
          description: good old plain product id from CRC/P&C, in six-digits-left-zero-padded-format; could be obsoleted in the future, in favour of 'price-plan id'
          type: string
          pattern: '\d{6}'
          example: '001249'
      example:
        fulfillmentAdministration: "Generiek Tariferen (RQR)"
        fulfillmentConfigurationId: "42"
        productId: "001290"
    InterestFulfillmentParameters:
      description: all the parameters needed to instantiate the product in Interest Calculation (RQR) \
        
        The minumum configuration item expected for most of the products in RQR would be the 'interest code'
      allOf:
        - $ref: '#/components/schemas/ProductImplementationBase'
      example:
        fulfillmentAdministration: "Interest Calculation (RQR)"
        fulfillmentConfigurationId: "42"
    BundlingFulfillmentParameters:
      description: all the parameters needed to instantiate the product in Interest Calculation (RQR) \
        
        The minumum configuration item expected for most of the products in APA would be the 'product bundle id\'
      allOf:
        - $ref: '#/components/schemas/ProductImplementationBase'
      properties:
        productBundleId:
          description: APA's internal bundle type id
          type: string
          pattern: '\d{4}'
          example: 1000
      example:
        fulfillmentAdministration: "Agreement Packaging Administration"
        fulfillmentConfigurationId: "42"
        productBundleId: 1000
    LimitsFulfillmentParameters:
      allOf:
        - $ref: '#/components/schemas/ProductImplementationBase'
      example:
        fulfillmentAdministration: "Limits"
        fulfillmentConfigurationId: "42"
    CashAndCardsFulfillmentParameters:
      allOf:
        - $ref: '#/components/schemas/ProductImplementationBase'
      example:
        fulfillmentAdministration: "Cash And Cards"
        fulfillmentConfigurationId: "42"
    CoreBankingFulfillmentParameters:
      allOf:
        - $ref: '#/components/schemas/ProductImplementationBase'
      example:
        fulfillmentAdministration: "Core Rekening Currant (CRC)"
        fulfillmentConfigurationId: "42"
    ProductFulfillmentParameters:
      type: array
      items:
        anyOf:
          - $ref: '#/components/schemas/AccountingFulfillmentParameters'
          - $ref: '#/components/schemas/BillingFulfillmentParameters'
          - $ref: '#/components/schemas/InterestFulfillmentParameters'
          - $ref: '#/components/schemas/BundlingFulfillmentParameters'
          - $ref: '#/components/schemas/LimitsFulfillmentParameters'
          - $ref: '#/components/schemas/CoreBankingFulfillmentParameters'
          - $ref: '#/components/schemas/CashAndCardsFulfillmentParameters'
    ConfigurationValues:
      description: a full set of concrete values chosen by the customer or by the process _for_ the customer
      type: array
      minItems: 1
      maxItems: 150
      items:
        $ref: '#/components/schemas/ConfigurationItemValue'
    ConfigurationItemValue:
      description: an instantiated configuration item with a concrete value
      required: 
        - itemId
      properties:
        itemId:
          description: the unique id of the configuration item
          type: string
          example: "09993d4a-e194-4c85-baf7-f67f8929669c"
        parentItemId:
          description: a mean to group configuration items. it could be a logical value for simple grouping or the id of another existing configuration item for creating a cascaded dependency.
        itemValue:
          description: the desired value for the configuration item, to be checked against the set of allowed values or other rules. the value should match the value type defined for the configuration item
          type: string
          example: "Mr. Injection"
externalDocs:
  description: please read more about the requirements and solution
  url: https://confluence.int.abnamro.com/display/GT/Catalog+for+Commerce
